version: '3.9'


services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ default communication port
      - "15672:15672"  # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: user   # Default RabbitMQ username
      RABBITMQ_DEFAULT_PASS: password  # Default RabbitMQ password
  #
  #  qdrant:
  #    image: qdrant/qdrant
  #    container_name: qdrant
  #    ports:
  #      - "6333:6333"  # Map port 6333 for API access
  #    volumes:
  #      - qdrant_storage:/qdrant/storage  # Persistent storage for Qdrant data

  api:
    build: api
    container_name: api
    ports:
      - "8000:8000"

  ml:
    build: ml_algo
    container_name: ml_algo

volumes:
  qdrant_storage: