version: '3.9'


services:
  #  flask_web:
  #    container_name: flask_web_container
  #    build: ./frontend
  #    ports:
  #      - "5001:5001"
  #    restart: unless-stopped
  #    command: python3 app.py
  #
  #  qdrant:
  #    image: qdrant/qdrant
  #    container_name: qdrant
  #    ports:
  #      - "6333:6333"  # Map port 6333 for API access
  #    volumes:
  #      - qdrant_storage:/qdrant/storage  # Persistent storage for Qdrant data

  api:
    build: api
    container_name: api
    ports:
      - "8000:8000"

volumes:
  qdrant_storage: